#!/usr/bin/env bash
# Sript to install certbot in Ubuntu 16.04 LTS

sudo apt-get update
sudo apt-get install snapd
sudo apt-get remove certbot
sudo snap install --classic certbot
sudo certbot certonly --standalone
sudo export LC_ALL="en_US.UTF-8"
sudo export LC_CTYPE="en_US.UTF-8"
