#!/usr/bin/env bash
# This script installs nginx in a local machine
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
chmod 666 /var/www/html/index.nginx-debian.html
chmod 666 /usr/share/nginx/html/index.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Holberton School" > /usr/share/nginx/html/index.html
service nginx restart 
