#!/usr/bin/env bash
# This script installs nginx in a local machine
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
touch /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
sed -i  's/# pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000/rewrite \/redirect_me\/   https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default
sudo service nginx restart
