#!/usr/bin/env bash
# Installs nginx, configures a redirection on /redirect_me
# and a custom 404 page

sudo apt-get update -y
sudo apt-get install nginx -y
sudo echo "Holberton School" > /var/www/html/index.html
sudo sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i '/server_name _;/a error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
