#!/usr/bin/env bash
# This script pings 5 times to a given IP as argument
if [[ $# -eq 0 ]];
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
else
    IP=$1
    ping -c5 "$IP"
fi
