#!/usr/bin/env bash
# Prints 'Holberton School' ten times using while flow control and if statement
x=1
while [ $x -le 10 ]
do
    echo "Holberton School"
    if [ $x -eq 9 ]
    then
        echo "Hi"
    fi
    x=$((x + 1))
done
