#!/usr/bin/env bash
# Script to set a basic Firewall
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw allow 8080
sudo ufw enable
sudo ufw reload
sudo ufw status verbose
